apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::816894938682:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::816894938682:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DH3S7H2U3OSW
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-12T10:36:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1513"
  uid: 56bfa95d-1850-4d6a-b593-459a36ce35a0
